"""Regenerate local-export images after changing img/tile.png."""
import base64
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
images = {
    name: 'data:image/png;base64,' + base64.b64encode((root / 'img' / name).read_bytes()).decode('ascii')
    for name in ('tile.png',)
}
(root / 'export-image.js').write_text(
    '// Generated by scripts/update-export-image.py.\n'
    f'window.localExportTiles = {json.dumps(images)};\n'
)
